<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.profiler</groupId>
    <artifactId>method-profiler-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>profiler-agent</module>
        <module>profiler-dashboard</module>
        <module>profiler-demo-app</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <bytebuddy.version>1.14.10</bytebuddy.version>
        <jackson.version>2.16.0</jackson.version>
    </properties>
</project>